### ISSUE TITLE
Import moe? 

### ISSUE THREAD

**Issue by daeunni** [tankche1/Mod-squad#2]
Hi, @tankche1, thanks for your nice work! 

btw, how can I import this one? 
```
from moe import MoE as MMoE
from moe import cvMoE
```

https://github.com/UMass-Foundation-Model/Mod-Squad/blob/1d17e81d090ac7e1a66dd420194c0b7679d820a4/models_moe.py#L16C1-L17C22

**Comment by daeunni** [comment]
Or will it override by `parallel_experts` ?

**Comment by daeunni** [comment]
The reason why I write this issue was about `TaskMoE` class at `models_moe.py`.
At the models_moe.py, your code seems to load `TaskMoE` using `from parallel_experts import RandomMoE, TaskMoE`. 
In addition, we use `TaskMoE` at the `MoEAttention` function. 

However, I found at the `MoEAttention` function, your code is not using `TaskMoE`
which is in the `Mod-Squad/parallel_linear/parallel_experts/moe.py`

**But I wanna customize your function `TaskMoE` in my research. 
May I ask what `TaskMoE` function are you using, and where is that function exactly?** 

Ty! :)

**Comment by tankche1** [comment]
I don't get your question. moe.py is in parallel_linear folders. They are different implementations of different MoE versions. The MoE in the paper vision uses 'from parallel_experts import TaskMoE'.

**Comment by daeunni** [comment]
Ah, it was my misunderstanding. I addressed it! Thank u!
