### ISSUE TITLE
HalfFloat causing expert_size_list.sum(0) != input.size(0)

### ISSUE THREAD

**Issue by YangSun22** [tankche1/Mod-squad#4]
File "/root/miniconda3/envs/obbdetection/lib/python3.7/site-packages/parallel_experts/parallel_experts.py", line 109, in forward
    results = ParallelLinear.apply(inputs, expert_size, self.w, self.b)
  File "/root/miniconda3/envs/obbdetection/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py", line 217, in decorate_fwd
    return fwd(*_cast(args, cast_inputs), **_cast(kwargs, cast_inputs))
  File "/root/miniconda3/envs/obbdetection/lib/python3.7/site-packages/parallel_experts/parallel_experts.py", line 15, in forward
    output = ParallelLinear.forward_scriptable(input, expert_size, weight, bias)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/root/miniconda3/envs/obbdetection/lib/python3.7/site-packages/parallel_experts/parallel_experts.py", line 29, in forward_scriptable
    
        expert_size_list: List[int] = expert_size.tolist()
        input_list = input.split(expert_size_list, dim=0)
                     ~~~~~~~~~~~ <--- HERE
        output_buf_list = output_buf.split(expert_size_list)
    
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 18816 (input tensor's size at dimension 0), but got split_sizes=[3766, 3670, 486, 2719, 2390, 1565, 1977, 2239]

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 65031) of binary: /root/miniconda3/envs/obbdetection/bin/python


moe.py--def compute_gating()
 input.size(0) ：              nonzeros = top_k_gates.nonzero().squeeze(-1)
expert_size_list.sum(0)：expert_size = (gates > 0).long().sum(0)

Maybe  torch.nonzero() and torch.tensor >0 have diffenrent way to compute

**Comment by tankche1** [comment]
I need more information on how you call the function. What is the batch size and GPU number?

**Comment by YangSun22** [comment]
Thank you for your attention.

GPUs: 2
BatchSize: 3
But  input of MoE is 17640 Tokens once forward.
This array length mismatch problem has only a small probability of occurring in a run. So I think it is caused by mixed precision training (FloatTensor and HalfFloatTensor).
Specifically there is a precision difference between these two Torch functions。
moe.py--def compute_gating()
1. input.size(0) ： nonzeros = top_k_gates**.nonzero()**.squeeze(-1)
2 .expert_size_list.sum(0)：expert_size = **(gates > 0)**.long().sum(0)

I've disabled mixing precision where I use MoE. No small chance of errors yet.

**Comment by YangSun22** [comment]
I take back what I said before. The code is still reporting errors after running almost 10,000 iterations.

**Comment by tankche1** [comment]
I think your training got a loss of Nan or something and this lead to this error. If the middle of a forward has a Nan in the feature it could cause this error. I am not sure why but I have seen this before. The precision just makes it longer to get NaN. If you set the learning rate to be very small, I expect this error will show up later.
