### ISSUE TITLE
How to test on Pascal-Context dataset?

### ISSUE THREAD

**Issue by MeteorsHub** [tankche1/Mod-squad#6]
The Taskonomy dataset is too large. Even the tiny-taskonomy is over 500GB. So how to test on Pascal-Context dataset as illustrated in the paper?
The paper said  the pascal-context includes "five task annotation of edge detection (Edge), semantic segmentation (Seg.), human parts segmentation (H.Parts), surface normals (Norm.), and saliency detection (Sal.)". But I can only find semantic segmentation in the pascal-context website. Is there a convinent way to download all the annotations?

**Comment by tankche1** [comment]
Please refer to https://github.com/VITA-Group/M3ViT  .  Our experiments are based on this repo.

**Comment by MeteorsHub** [comment]
Thanks for the suggetion. 
Another questions. I found that M3ViT use multiple-conv layers as each task head decoder. However, in your code the head is a single MLP layer to the rearranged tokens from the vit-backbone. Which one did you use when you conducted evaluation on Pascal-Context?

**Comment by tankche1** [comment]
We follow M3ViT in Pascal-Context
