### ISSUE TITLE
why compute top k gate do not use noisy

### ISSUE THREAD

**Issue by Lucenova** [tankche1/Mod-squad#8]
![image](https://github.com/UMass-Foundation-Model/Mod-Squad/assets/24931666/d607a626-15c3-4e00-9a50-fb69bc87e459)

**Comment by tankche1** [comment]
In practice, we don't find much difference whether we add noise or not.

**Comment by Lucenova** [comment]
By the way, I find about loss, you do not use switchloss and zloss even you compute them
